# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 20:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('pareja', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('1', 'No Autorizado'), ('2', 'Autorizado'), ('3', 'Enviado')], default='1', max_length=1)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Directorios',
                'verbose_name': 'Directorio',
            },
        ),
    ]
