# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 23:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acuse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.TextField()),
                ('update', models.DateTimeField(auto_now=True)),
                ('timestamps', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Acuses',
                'verbose_name': 'Acuse',
            },
        ),
        migrations.CreateModel(
            name='Directorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profesion', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre', models.CharField(max_length=150)),
                ('pareja', models.CharField(blank=True, max_length=150, null=True)),
                ('cargo', models.TextField(blank=True, null=True)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(default='1', max_length=1)),
                ('modificado', models.CharField(max_length=150, null=True)),
                ('cdmx', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Directorios',
                'verbose_name': 'Directorio',
            },
        ),
        migrations.CreateModel(
            name='Historial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamps', models.DateTimeField(auto_now=True)),
                ('directorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Directorio')),
            ],
            options={
                'verbose_name_plural': 'Historiales',
                'verbose_name': 'Historial',
            },
        ),
        migrations.CreateModel(
            name='Obsequio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('entregado', models.IntegerField(blank=True, null=True)),
                ('existencia', models.IntegerField(blank=True, null=True)),
                ('default', models.BooleanField(default=False)),
                ('timestamps', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Obsequios',
                'verbose_name': 'Obsequio',
            },
        ),
        migrations.AddField(
            model_name='historial',
            name='obsequio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Obsequio'),
        ),
        migrations.AddField(
            model_name='acuse',
            name='obsequio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='directorio.Obsequio'),
        ),
    ]
