# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio',
            name='status',
            field=models.CharField(default='1', max_length=1),
        ),
    ]
