# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='añadir',
            field=models.BooleanField(default=False),
        ),
    ]
