# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-02 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acuse',
            name='obsequio',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='directorio.Obsequio'),
        ),
    ]
