# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 17:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_auto_20161102_0436'),
    ]

    operations = [
        migrations.AddField(
            model_name='acuse',
            name='defaut',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='modificado',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='directorio',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
