# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-13 13:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0002_directorio_añadir'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directorio',
            old_name='añadir',
            new_name='lista',
        ),
    ]
