# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 22:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_auto_20161018_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='modificado',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
