# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-03 17:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0003_auto_20161103_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='acuse',
            old_name='defaut',
            new_name='default',
        ),
    ]
