# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 22:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_directorio_modificado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='directorio',
            name='modificado',
        ),
    ]
