# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-04 02:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0004_auto_20161103_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsequio',
            name='entregado',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='obsequio',
            name='existencia',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
