# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-05 00:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0005_auto_20161103_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio',
            name='nombre',
            field=models.CharField(max_length=150, unique=True),
        ),
    ]
