# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-18 22:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0006_auto_20161018_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='directorio',
            name='modificado',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
