# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-24 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0008_directorio_eliminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='directorio',
            name='eliminado',
            field=models.CharField(default='0', max_length=1, null=True),
        ),
    ]
