# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0012_auto_20161024_1529'),
    ]

    operations = [
        migrations.CreateModel(
            name='Obsequio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('cantidad', models.IntegerField()),
                ('entregado', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Obsequios',
                'verbose_name': 'Obsequio',
            },
        ),
    ]
