# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-10-25 15:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directorio', '0013_obsequio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obsequio',
            name='entregado',
            field=models.IntegerField(null=True),
        ),
    ]
